### ISSUE TITLE
How do i disable the accents

### ISSUE THREAD

**Issue by stephenajulu** [stackbithq/stackbit-theme-phantom#3]
Hi, how are you?
I am using this theme and i wanted to know how to disable the accents on posts?
Or put 1 accent from all my posts.
Also kindly tell me how to add dark mode or simply make the website dark.
Thank you

**Comment by stephenajulu** [comment]
Also how can i add categories, tags and authors?

**Comment by smnh** [comment]
Hi @stephenajulu,

To disable the accents and make the site darker, you will need to edit CSS files in the generated site to make it look the way you want. The theme gives you a starting point. From there, you can take it anywhere you want by editing CSS or page templates. Depends on which SSG you have select when you generate a site using [stackbit site builder](https://app.stackbit.com)

Regarding categories, tags and authors. You can take a look at our [Starter theme](https://github.com/stackbithq/stackbit-theme-starter) to see how to create categories, tags and authors.
If you would like to use Phantom theme with these features, I suggest generating one site using the Starter theme, and one site using the Phantom theme. Then you can copy the code related to desired features.

**Comment by stephenajulu** [comment]
thank you
